### ISSUE TITLE
Sass Converter Error

### ISSUE THREAD

**Issue by allanjpb** [DevTips/Artists-Theme#106]
I followed instructions 

allan@allan-pc:~/test/Artists-Theme$ jekyll serve --watch --trace
Configuration file: /home/allan/test/Artists-Theme/_config.yml
            Source: /home/allan/test/Artists-Theme
       Destination: /home/allan/test/Artists-Theme/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Conversion error: Jekyll::Converters::Sass encountered an error while converting 'assets/css/all.sass':
                    Error: Invalid CSS after "$accent": expected 1 selector or at-rule, was ": #c99065;" on line 15:1 of all.sass >> $accent: #c99065; ^ 
Traceback (most recent call last):
	28: from /home/allan/gems/bin/jekyll:23:in `<main>'
	27: from /home/allan/gems/bin/jekyll:23:in `load'
	26: from /home/allan/gems/gems/jekyll-4.0.0/exe/jekyll:15:in `<top (required)>'
	25: from /home/allan/gems/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	24: from /home/allan/gems/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	23: from /home/allan/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	22: from /home/allan/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	21: from /home/allan/gems/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	20: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
	19: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `process_with_graceful_fail'
	18: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `each'
	17: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:89:in `block in process_with_graceful_fail'
	16: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:36:in `process'
	15: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/commands/build.rb:65:in `build'
	14: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/command.rb:28:in `process_site'
	13: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:76:in `process'
	12: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:202:in `render'
	11: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `render_pages'
	10: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:515:in `each'
	 9: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:516:in `block in render_pages'
	 8: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/site.rb:523:in `render_regenerated'
	 7: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:63:in `run'
	 6: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:84:in `render_document'
	 5: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `convert'
	 4: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `reduce'
	 3: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:100:in `each'
	 2: from /home/allan/gems/gems/jekyll-4.0.0/lib/jekyll/renderer.rb:102:in `block in convert'
	 1: from /home/allan/gems/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:179:in `convert'
/home/allan/gems/gems/jekyll-sass-converter-2.0.1/lib/jekyll/converters/scss.rb:187:in `rescue in convert': Error: Invalid CSS after "$accent": expected 1 selector or at-rule, was ": #c99065;" (Jekyll::Converters::Scss::SyntaxError)
        on line 15:1 of all.sass
>> $accent: #c99065;

I am completely new to SCSS

Can you offer any advice
Regards
Allan

**Comment by mcumiskey** [comment]
The line that solves the sass issue (based on @frobnitzem's solution!) is changing line 13 in all.sass to 

$projects: ( {% for project in site.data.settings.projects %} "{{ project.folder }}", {% endfor %} )

I am also new to sass, but it seems as though adding brackets (square or round) stops the converter stops throwing the issue.
